"""your message

Revision ID: 0d975ee8db00
Revises: 4938776fe532
Create Date: 2025-06-22 17:33:12.163911

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0d975ee8db00'
down_revision = '4938776fe532'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('occupation', sa.String(length=128), nullable=True))
        batch_op.add_column(sa.Column('company', sa.String(length=128), nullable=True))
        batch_op.add_column(sa.Column('income', sa.String(length=32), nullable=True))
        batch_op.add_column(sa.Column('preferred_gender', sa.String(length=16), nullable=True))
        batch_op.add_column(sa.Column('bio', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('bio')
        batch_op.drop_column('preferred_gender')
        batch_op.drop_column('income')
        batch_op.drop_column('company')
        batch_op.drop_column('occupation')

    # ### end Alembic commands ###
