"""initial tables

Revision ID: 6a8464e3e617
Revises: 2c1737aa91dc
Create Date: 2025-06-20 17:26:15.594824

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '6a8464e3e617'
down_revision = '2c1737aa91dc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('people',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('gender', sa.String(length=10), nullable=True),
    sa.Column('age', sa.Integer(), nullable=True),
    sa.Column('contact', sa.String(length=20), nullable=True),
    sa.Column('city', sa.String(length=100), nullable=True),
    sa.Column('occupation', sa.String(length=50), nullable=True),
    sa.Column('budget', sa.Integer(), nullable=True),
    sa.Column('hobbies', postgresql.ARRAY(sa.String()), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('preferences', postgresql.JSON(astext_type=sa.Text()), nullable=True),
    sa.Column('looking_for', sa.String(length=20), nullable=True),
    sa.Column('profile_picture', sa.String(length=300), nullable=True),
    sa.Column('government_id', sa.String(length=300), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('properties',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.Column('contact', sa.String(length=20), nullable=True),
    sa.Column('city', sa.String(length=100), nullable=True),
    sa.Column('address', sa.String(length=200), nullable=True),
    sa.Column('rent', postgresql.JSON(astext_type=sa.Text()), nullable=True),
    sa.Column('security_amount', sa.NUMERIC(precision=10, scale=2), nullable=True),
    sa.Column('electricity_rate', sa.NUMERIC(precision=5, scale=2), nullable=True),
    sa.Column('amenities', postgresql.ARRAY(sa.String()), nullable=True),
    sa.Column('room_types', postgresql.JSON(astext_type=sa.Text()), nullable=True),
    sa.Column('furnished', sa.Boolean(), nullable=True),
    sa.Column('food_included', sa.Boolean(), nullable=True),
    sa.Column('laundry_available', sa.Boolean(), nullable=True),
    sa.Column('available_from', sa.Date(), nullable=True),
    sa.Column('gender_preference', sa.String(length=20), nullable=True),
    sa.Column('distance_from_college_or_office', sa.String(length=50), nullable=True),
    sa.Column('pictures', postgresql.ARRAY(sa.String()), nullable=True),
    sa.Column('government_id', sa.String(length=300), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=150), nullable=False),
    sa.Column('email', sa.String(length=150), nullable=False),
    sa.Column('password_hash', sa.String(length=256), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=True),
    sa.Column('gender', sa.String(length=10), nullable=True),
    sa.Column('age', sa.Integer(), nullable=True),
    sa.Column('contact', sa.String(length=15), nullable=True),
    sa.Column('address', sa.String(length=200), nullable=True),
    sa.Column('hobbies', postgresql.ARRAY(sa.String()), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('username')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('users')
    op.drop_table('properties')
    op.drop_table('people')
    # ### end Alembic commands ###
